import { Router } from 'express';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import * as XLSX from 'xlsx';
import PDFDocument from 'pdfkit';
import { db } from '../db';
import { config } from '../config';
import { requireAuth, requirePermission } from '../middleware/auth';
import { guardGuestDatasetParam, guardGuestDatasetQueryParams } from '../middleware/guestScope';
import { asyncHandler, HttpError } from '../middleware/errors';
import { audit } from '../services/audit';
import * as svc from '../services/analytics';

fs.mkdirSync(config.exportDir, { recursive: true });

/**
 * Spreadsheet formula-injection protection: values beginning with =, +, -, @
 * (or tab/CR variants) would execute as formulas when the export is opened in
 * Excel. Such strings are prefixed with a single quote, which Excel renders
 * as plain text.
 */
function sanitizeCell(v: unknown): unknown {
  if (typeof v !== 'string') return v;
  if (/^[=+\-@\t\r]/.test(v)) return `'${v}`;
  return v;
}

function sanitizeRows(rows: object[]): Record<string, unknown>[] {
  return rows.map((r) => Object.fromEntries(Object.entries(r).map(([k, v]) => [k, sanitizeCell(v)])));
}

export const exportsRouter = Router();
exportsRouter.use(requireAuth, requirePermission('export'), guardGuestDatasetQueryParams);
// Covers /dataset/:id, /analysis/:stockDatasetId, /report/:stockDatasetId.
exportsRouter.param('id', guardGuestDatasetParam);
exportsRouter.param('stockDatasetId', guardGuestDatasetParam);

const TABLE_FOR_KIND: Record<string, string> = {
  stock: 'stock_items',
  movements: 'movements',
  material_master: 'material_master',
  physical_inventory: 'physical_inventory',
};

async function recordExport(userId: number, tenantId: string, datasetId: number | null, type: string, filename: string, ip?: string) {
  await db('exports').insert({ user_id: userId, tenant_id: tenantId, dataset_id: datasetId, export_type: type, filename });
  await audit({ action: 'export', userId, tenantId, entityType: 'dataset', entityId: datasetId ?? undefined, newValue: { type, filename }, sourceIp: ip });
}

/** Dataset rows as XLSX or CSV. */
exportsRouter.get('/dataset/:id', asyncHandler(async (req, res) => {
  const ds = await db('datasets').where({ id: Number(req.params.id), tenant_id: req.user!.tenantId }).first();
  if (!ds) throw new HttpError(404, 'Dataset not found');
  const format = req.query.format === 'csv' ? 'csv' : 'xlsx';
  const rows = await db(TABLE_FOR_KIND[ds.kind]).where({ dataset_id: ds.id, tenant_id: req.user!.tenantId }).select('*');
  const cleaned = rows.map(({ id: _id, dataset_id: _d, ...rest }: Record<string, unknown>) => rest);

  const ws = XLSX.utils.json_to_sheet(sanitizeRows(cleaned));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Data');

  const metaWs = XLSX.utils.json_to_sheet([
    { field: 'Dataset', value: `${ds.name} v${ds.version}` },
    { field: 'Kind', value: ds.kind },
    { field: 'Period', value: `${ds.period_start ?? 'n/a'} .. ${ds.period_end ?? 'n/a'}` },
    { field: 'Rows', value: ds.row_count },
    { field: 'Quality score', value: ds.quality_scores ? JSON.parse(ds.quality_scores).overall : 'n/a' },
    { field: 'Generated', value: new Date().toISOString() },
    { field: 'Generated by', value: req.user!.email },
  ]);
  XLSX.utils.book_append_sheet(wb, metaWs, 'Report Info');

  const filename = `dataset-${ds.id}-${ds.name.replace(/[^\w\-]+/g, '_')}.${format}`;
  const buf = XLSX.write(wb, { type: 'buffer', bookType: format === 'csv' ? 'csv' : 'xlsx' }) as Buffer;
  await recordExport(req.user!.id, req.user!.tenantId, ds.id, `dataset_${format}`, filename, req.ip);
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Content-Type', format === 'csv' ? 'text/csv' : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.send(buf);
}));

/** Analysis workbook: position, aging, categories, shortage (+excess with movements). */
exportsRouter.get('/analysis/:stockDatasetId', asyncHandler(async (req, res) => {
  const stockId = Number(req.params.stockDatasetId);
  const ds = await svc.requireDataset(stockId, 'stock');
  const movementsId = req.query.movementsDatasetId ? Number(req.query.movementsDatasetId) : undefined;

  const position = await svc.inventoryPosition(stockId);
  const aging = await svc.agingAnalysis(stockId, 'last_movement');
  const categories = await svc.movementCategoryAnalysis(stockId, movementsId);
  const shortage = await svc.shortageAnalysis(stockId, movementsId);

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet([
    { kpi: 'Total value', value: position.totals.value },
    { kpi: 'Materials', value: position.totals.materials },
    { kpi: 'Blocked value', value: position.totals.blocked },
    { kpi: 'Slow-moving value', value: categories.summary.slowMoving.value },
    { kpi: 'Non-moving value', value: categories.summary.nonMoving.value },
    { kpi: 'Shortage-risk materials', value: shortage.results.length },
  ]), 'KPIs');
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(sanitizeRows(position.byGroup)), 'By Group');
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(sanitizeRows(aging.summary)), 'Aging');
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(sanitizeRows(categories.results)), 'Movement Categories');
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(sanitizeRows(shortage.results)), 'Shortage Risks');
  if (movementsId) {
    const excess = await svc.excessAnalysis(stockId, 'above_coverage_target', movementsId);
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(sanitizeRows(excess.results)), 'Excess Stock');
  }
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet([
    { field: 'Dataset', value: `${ds.name}` },
    { field: 'Period', value: `${ds.period_start ?? 'n/a'} .. ${ds.period_end ?? 'n/a'}` },
    { field: 'Generated', value: new Date().toISOString() },
    { field: 'Generated by', value: req.user!.email },
    { field: 'Note', value: 'All classifications use the configured thresholds; see Administration > Configuration.' },
  ]), 'Report Info');

  const filename = `analysis-${ds.id}.xlsx`;
  const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
  await recordExport(req.user!.id, req.user!.tenantId, ds.id, 'analysis_xlsx', filename, req.ip);
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.send(buf);
}));

/** Management PDF summary. */
exportsRouter.get('/report/:stockDatasetId', asyncHandler(async (req, res) => {
  const stockId = Number(req.params.stockDatasetId);
  const ds = await svc.requireDataset(stockId, 'stock');
  const movementsId = req.query.movementsDatasetId ? Number(req.query.movementsDatasetId) : undefined;
  const currency = await svc.getConfig('currency', 'USD');

  const position = await svc.inventoryPosition(stockId);
  const aging = await svc.agingAnalysis(stockId, 'last_movement');
  const categories = await svc.movementCategoryAnalysis(stockId, movementsId);
  const shortage = await svc.shortageAnalysis(stockId, movementsId);
  const health = await svc.healthAnalysis(stockId, movementsId);

  const filename = `management-report-${ds.id}-${crypto.randomBytes(4).toString('hex')}.pdf`;
  const filePath = path.join(config.exportDir, filename);
  const doc = new PDFDocument({ margin: 50, info: { Title: 'Inventory Management Report' } });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  doc.fontSize(20).text('Kynox Supply Chain Intelligence', { align: 'left' });
  doc.fontSize(14).fillColor('#555').text('Inventory Management Report');
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#000')
    .text(`Dataset: ${ds.name} (v${(ds as unknown as { version?: number }).version ?? 1})`)
    .text(`Period: ${ds.period_start ?? 'n/a'} to ${ds.period_end ?? 'n/a'}`)
    .text(`Generated: ${new Date().toISOString()} by ${req.user!.email}`)
    .text(`Currency: ${currency}`);
  doc.moveDown();

  doc.fontSize(13).text('Headline KPIs', { underline: true }).moveDown(0.3);
  doc.fontSize(10);
  const kpis: [string, string][] = [
    ['Total inventory value', `${position.totals.value.toLocaleString()} ${currency}`],
    ['Materials', String(position.totals.materials)],
    ['Blocked value', `${position.totals.blocked.toLocaleString()} ${currency}`],
    ['Slow-moving value', `${categories.summary.slowMoving.value.toLocaleString()} ${currency}`],
    ['Non-moving value', `${categories.summary.nonMoving.value.toLocaleString()} ${currency}`],
    ['Shortage-risk materials', String(shortage.results.length)],
    ['Inventory health score', `${health.score} / 100`],
  ];
  for (const [k, v] of kpis) doc.text(`${k}: ${v}`);
  doc.moveDown();

  doc.fontSize(13).text('Inventory Aging', { underline: true }).moveDown(0.3);
  doc.fontSize(10);
  for (const b of aging.summary) {
    doc.text(`${b.bucket}: ${b.materialCount} materials, value ${b.value.toLocaleString()} ${currency}`);
  }
  doc.moveDown();

  doc.fontSize(13).text('Top Shortage Risks', { underline: true }).moveDown(0.3);
  doc.fontSize(10);
  for (const s of shortage.results.slice(0, 10)) {
    doc.text(`${s.material} [${s.risk}] — ${s.reason}`);
  }
  if (shortage.results.length === 0) doc.text('No shortage risks detected with the available data.');
  doc.moveDown();

  doc.fontSize(13).text('Method Notes and Assumptions', { underline: true }).moveDown(0.3);
  doc.fontSize(9).fillColor('#444');
  doc.text('Aging basis: days since last movement, bucketed per configured aging buckets.');
  doc.text('Slow-moving / non-moving classification per configured day thresholds; excess per coverage-target method.');
  doc.text('Health score components and weights: ' + health.explanation.join(' | '));
  if (!movementsId) doc.text('Limitation: no movements dataset linked — consumption-based KPIs unavailable.');

  doc.end();
  await new Promise<void>((resolve, reject) => {
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  await recordExport(req.user!.id, req.user!.tenantId, ds.id, 'management_pdf', filename, req.ip);
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Content-Type', 'application/pdf');
  fs.createReadStream(filePath).pipe(res);
}));
